### ISSUE TITLE
How to install additional packages for judge env (e.g. numpy)

### ISSUE THREAD

**Issue by Ali-Toosi** [DMOJ/judge-server#865]
Hi,
This isn't exactly an issue but is more of a question - which I couldn't find an answer for anywhere. This seems to be the closest item which is not still the same: https://github.com/DMOJ/judge-server/issues/364
How can we add support for additional python packages to the judge? So the submissions would be allowed to import say numpy.
I have tried installing those additional packages in the judge-tier1 Docker image but they are still not accessible from within the submission, which I believe is because some virtualization of submission run environment.
Is there a way to add additional packages?

**Comment by Xyene** [comment]
Since this is not a supported configuration, you will have to modify the Python executor to not pass `-S` to the submission here:

https://github.com/DMOJ/judge-server/blob/3ca9661f79afd139017dbe9073f09b635b5d94f0/dmoj/executors/python_executor.py#L33-L34

You'll probably also have to modify `extra_fs` in your judge configuration to allow nonstandard paths, or modify the executor to set `fs` to a list of regexes that should be allowed. You can take a look at other executors for examples.

**Comment by Ali-Toosi** [comment]
Could I ask you for further support on this? Really appreciate it. I have removed the -S and also configured executor fs and it definitely did make a change but not fixed yet. Before, when I imported numpy it said ModuleNotFoundError but now it says `interrupt`. Would you have a guess as to what the issue is?
The changes:
```
    return [self.get_command(), '-B' + ('u' if self.unbuffered else ''), self._loader, self._code]
```
and fs in PY3.py:
```
    fs = ['.*numpy.*', '.*pandas.*']

```
Error:
![image](https://user-images.githubusercontent.com/3009161/123798680-c7ddfc80-d92a-11eb-954b-020cdef336a1.png)
![image](https://user-images.githubusercontent.com/3009161/123798702-cf9da100-d92a-11eb-9fa8-b2210ab2f15b.png)

Thank you once again for your help : )

**Comment by ktikhonov** [comment]
This:
    fs = ['.*numpy.*', '.*pandas.*']
does not seem to work currently, does it? (It does not accept strings for filesystem rules).
